// Mocks generated by Mockito 5.4.4 from annotations
// in notes_web_app/test/screen/note_detail_page_screen_test/note_detail_page_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notes_web_app/src/data/services/notes_api_service.dart' as _i3;
import 'package:notes_web_app/src/domain/model/note.dart' as _i2;
import 'package:notes_web_app/src/domain/model/tag.dart' as _i5;
import 'package:notes_web_app/src/domain/provider/note_provider.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNote_0 extends _i1.SmartFake implements _i2.Note {
  _FakeNote_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesApiService extends _i1.Mock implements _i3.NotesApiService {
  MockNotesApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Note>> getNotes() => (super.noSuchMethod(
        Invocation.method(
          #getNotes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Note>>.value(<_i2.Note>[]),
      ) as _i4.Future<List<_i2.Note>>);

  @override
  _i4.Future<_i2.Note> getNoteById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Note>.value(_FakeNote_0(
          this,
          Invocation.method(
            #getNoteById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Note>);

  @override
  _i4.Future<void> addNote(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #addNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateNote(
    int? id,
    _i2.Note? note,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [
            id,
            note,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNote(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Tag>> getTags() => (super.noSuchMethod(
        Invocation.method(
          #getTags,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Tag>>.value(<_i5.Tag>[]),
      ) as _i4.Future<List<_i5.Tag>>);

  @override
  _i4.Future<void> addTag(_i5.Tag? tag) => (super.noSuchMethod(
        Invocation.method(
          #addTag,
          [tag],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> associateTagsWithNote({
    required int? noteId,
    required List<_i5.Tag>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #associateTagsWithNote,
          [],
          {
            #noteId: noteId,
            #tags: tags,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTag(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NoteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNoteProvider extends _i1.Mock implements _i6.NoteProvider {
  MockNoteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Note> get notes => (super.noSuchMethod(
        Invocation.getter(#notes),
        returnValue: <_i2.Note>[],
      ) as List<_i2.Note>);

  @override
  List<_i5.Tag> get tags => (super.noSuchMethod(
        Invocation.getter(#tags),
        returnValue: <_i5.Tag>[],
      ) as List<_i5.Tag>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setSortBy(String? sortBy) => super.noSuchMethod(
        Invocation.method(
          #setSortBy,
          [sortBy],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> fetchNotes() => (super.noSuchMethod(
        Invocation.method(
          #fetchNotes,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> fetchTags() => (super.noSuchMethod(
        Invocation.method(
          #fetchTags,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> add(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> update(
    _i2.Note? oldNote,
    _i2.Note? newNote,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            oldNote,
            newNote,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(_i2.Note? note) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addTag(_i5.Tag? tag) => (super.noSuchMethod(
        Invocation.method(
          #addTag,
          [tag],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTag(_i5.Tag? tag) => (super.noSuchMethod(
        Invocation.method(
          #deleteTag,
          [tag],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
